name: Docker CI
on:
  push:
    branches:
      - main

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: |
          docker build . -t time





